### ISSUE TITLE
Bulletin of the British Museum (Natural History). Zoology

### ISSUE THREAD

**Issue by rdmpage** [gbhl/bhl-segment-definition#1]
Key | Value
--|--
Title | Bulletin of the British Museum (Natural History). Zoology
BHL Title ID | [2202](https://www.biodiversitylibrary.org/bibliography/2202)
ISSN | 0007-1498
Thumbnail | <img src="https://user-images.githubusercontent.com/83306/142288626-555550d7-6752-42f0-a5b0-6f933f1675bd.jpg" width="100px">
Segmentation | <img src="https://rdmpage.github.io/bhl-article-coverage/2202.png"> [View segmentation in BioStor](https://rdmpage.github.io/bhl-article-coverage/2202.html)
Example DOI | https://doi.org/10.5962/p.314117
WikiData | [Q21385105](http://alec-demo.herokuapp.com/Q21385105)

**Comment by swlny** [comment]
Article definition is especially sparse in the first issues. These issues include a table of contents/ index that might be useful source of author names, titles and starting page numbers.
